version: '3.8'

services:

  db:
    image: postgres:16-alpine
    container_name: my-postgres-db
    restart: unless-stopped
    #command: -c 'max_connections=2000'
    environment:
      POSTGRES_DB: GhazaSystemDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5444:5432"

  api:
    container_name: my-api
    build:
      context: ./src
      dockerfile: GhazaSystem.Api/Dockerfile
    ports:
      #- "8001:8081"
      - "8000:8080" # پورت 8080 کانتینر را به پورت 8000 کامپیوتر شما وصل می‌کند
    depends_on:
      - db
    #  - rabbitmq



  frontend:
    build:
      context: ./src
      dockerfile: ./Dockerfile
    ports:
      - "7000:8080"
      #- "7001:443" # برای Blazor WebAssembly
      #- "5001:5001"  # برای Blazor Server
    #depends_on:
    environment:
      # ⚠️ تغییر ۱: استفاده از ports برای Kestrel
      - ASPNETCORE_HTTP_PORTS=8080
      # ⚠️ تغییر ۲: تنظیم متغیر محیطی برای Public URL
      # این متغیر به Kestrel کمک می‌کند تا URL های صحیح را تولید کند (بخصوص برای SignalR)
      - ASPNETCORE_URLS=http://+:8080 
      - ASPNETCORE_ENVIRONMENT=Development # یا Production
      # اگر همچنان مشکل پابرجاست، این متغیر را اضافه کنید:
      - DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0
    volumes:
      - Front:/app/wwwroot
      - foodphotos:/app/wwwroot/image/foods
    depends_on:
     - api

volumes:
  postgres_data:
   driver: local
  Front:
   driver: local  
  foodphotos:
   driver: local